EMAIL_MAX_LENGTH = 254

USERNAME_MAX_LENGTH = 30
USERNAME_MIN_LENGTH = 1

PASSWORD_MAX_LENGTH = 50
PASSWORD_MIN_LENGTH = 15

ACCOUNT_CREATION_TOKEN_LENGTH = 30
ACCOUNT_DELETION_TOKEN_LENGTH = 30
ACCOUNT_RECOVERY_TOKEN_LENGTH = 30
ACCOUNT_BACKUP_KEY_LENGTH = 30

SESSION_TOKEN_LENGTH = 30
SESSION_MAX_DURATION_MINS = 120

STATUS_MAX_LENGTH = 200
STATUS_MIN_LENGTH = 0

USER_MAX_POSTS = 200
USER_MAX_POSTS_PER_DAY = 5
POST_MAX_LENGTH = 10000
POST_TITLE_MAX_LENGTH = 100

FRIEND_REQUESTS_MAX_PER_DAY = 20

USER_MAX_IMAGES = 50

COMMENT_MAX_LENGTH = 200
USER_MAX_COMMENTS_PER_DAY = 50

BUG_REPORT_MAX_LENGTH = 5000
BUG_REPORT_MIN_LENGTH = 100
