LOG_CREATIONS = True
LOG_DELETIONS = True
LOG_RECOVERY = True
LOG_LOGINS = True

LOG_USERNAME_CHANGE = True
LOG_EMAIL_CHANGE = True

LOG_CREATE_POST = True
LOG_DELETE_POST = True
LOG_CREATE_IMAGE = True
LOG_DELETE_IMAGE = True

LOG_SUSPEND = True
LOG_UNSUSPEND = True
LOG_ADMIN_DELETION = True
